// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhA6dABGAS_MraUodaV3mXJBreRJnkoqE',
    appId: '1:535959212493:web:5aa9d3a8ef3049c3b37484',
    messagingSenderId: '535959212493',
    projectId: 'kvsampleproject',
    authDomain: 'kvsampleproject.firebaseapp.com',
    storageBucket: 'kvsampleproject.appspot.com',
    measurementId: 'G-N1920V2KZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVfcZv_DjYB3oHm17roahD_0RpQHtSOF4',
    appId: '1:535959212493:android:51d9f72215e0ef83b37484',
    messagingSenderId: '535959212493',
    projectId: 'kvsampleproject',
    storageBucket: 'kvsampleproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQBkpS37DAbi_DfWlCi7ggMGRQtD_Ck0s',
    appId: '1:535959212493:ios:96142ba7f835ac18b37484',
    messagingSenderId: '535959212493',
    projectId: 'kvsampleproject',
    storageBucket: 'kvsampleproject.appspot.com',
    iosBundleId: 'com.example.loginTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQBkpS37DAbi_DfWlCi7ggMGRQtD_Ck0s',
    appId: '1:535959212493:ios:96142ba7f835ac18b37484',
    messagingSenderId: '535959212493',
    projectId: 'kvsampleproject',
    storageBucket: 'kvsampleproject.appspot.com',
    iosBundleId: 'com.example.loginTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhA6dABGAS_MraUodaV3mXJBreRJnkoqE',
    appId: '1:535959212493:web:17a0c6d15a4398aab37484',
    messagingSenderId: '535959212493',
    projectId: 'kvsampleproject',
    authDomain: 'kvsampleproject.firebaseapp.com',
    storageBucket: 'kvsampleproject.appspot.com',
    measurementId: 'G-K4L0F6GENN',
  );
}
